version = 1

test_patterns = [
  "test/**",
  "**/*_test.go"
]

exclude_patterns = ["**/*_pb.go"]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/sge-network/sge"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "gofumpt"