// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sge/bet/bet.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Bet_OddsType int32

const (
	// Invalid odd type
	Bet_ODD_TYPE_INVALID Bet_OddsType = 0
	// Decimal odds type
	Bet_ODD_TYPE_DECIMAL Bet_OddsType = 1
	// Fractional odds type
	Bet_ODD_TYPE_FRACTIONAL Bet_OddsType = 2
	// American odds type
	Bet_ODD_TYPE_AMERICAN Bet_OddsType = 3
)

var Bet_OddsType_name = map[int32]string{
	0: "ODD_TYPE_INVALID",
	1: "ODD_TYPE_DECIMAL",
	2: "ODD_TYPE_FRACTIONAL",
	3: "ODD_TYPE_AMERICAN",
}

var Bet_OddsType_value = map[string]int32{
	"ODD_TYPE_INVALID":    0,
	"ODD_TYPE_DECIMAL":    1,
	"ODD_TYPE_FRACTIONAL": 2,
	"ODD_TYPE_AMERICAN":   3,
}

func (x Bet_OddsType) String() string {
	return proto.EnumName(Bet_OddsType_name, int32(x))
}

func (Bet_OddsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9bc076bb1a4d9f6e, []int{0, 0}
}

//Status of the Bet.
type Bet_Status int32

const (
	//the unknown status
	Bet_STATUS_INVALID Bet_Status = 0
	//placed bet placed and waiting for result
	Bet_STATUS_PLACED Bet_Status = 1
	//canceled by Bettor
	Bet_STATUS_CANCELLED Bet_Status = 2
	//there was an abort because of force like match canceled or system.
	Bet_STATUS_ABORTED Bet_Status = 3
	//pending for any reason like DVM , see BetEventStatus on this case.
	Bet_STATUS_PENDING Bet_Status = 4
	//the result of the bet is decelerated.
	Bet_STATUS_RESULT_DECLARED Bet_Status = 5
	//the bet is settled.
	Bet_STATUS_SETTLED Bet_Status = 6
)

var Bet_Status_name = map[int32]string{
	0: "STATUS_INVALID",
	1: "STATUS_PLACED",
	2: "STATUS_CANCELLED",
	3: "STATUS_ABORTED",
	4: "STATUS_PENDING",
	5: "STATUS_RESULT_DECLARED",
	6: "STATUS_SETTLED",
}

var Bet_Status_value = map[string]int32{
	"STATUS_INVALID":         0,
	"STATUS_PLACED":          1,
	"STATUS_CANCELLED":       2,
	"STATUS_ABORTED":         3,
	"STATUS_PENDING":         4,
	"STATUS_RESULT_DECLARED": 5,
	"STATUS_SETTLED":         6,
}

func (x Bet_Status) String() string {
	return proto.EnumName(Bet_Status_name, int32(x))
}

func (Bet_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9bc076bb1a4d9f6e, []int{0, 1}
}

//Result of the bet.
type Bet_Result int32

const (
	//the invalid or unknown
	Bet_RESULT_INVALID Bet_Result = 0
	// the result is not decelerated yet.
	Bet_RESULT_PENDING Bet_Result = 1
	// bet is won
	Bet_RESULT_WON Bet_Result = 2
	// bet is lost
	Bet_RESULT_LOST Bet_Result = 3
	// bet is draw
	Bet_RESULT_DRAW Bet_Result = 4
	// bet is aborted
	Bet_RESULT_ABORTED Bet_Result = 5
)

var Bet_Result_name = map[int32]string{
	0: "RESULT_INVALID",
	1: "RESULT_PENDING",
	2: "RESULT_WON",
	3: "RESULT_LOST",
	4: "RESULT_DRAW",
	5: "RESULT_ABORTED",
}

var Bet_Result_value = map[string]int32{
	"RESULT_INVALID": 0,
	"RESULT_PENDING": 1,
	"RESULT_WON":     2,
	"RESULT_LOST":    3,
	"RESULT_DRAW":    4,
	"RESULT_ABORTED": 5,
}

func (x Bet_Result) String() string {
	return proto.EnumName(Bet_Result_name, int32(x))
}

func (Bet_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9bc076bb1a4d9f6e, []int{0, 2}
}

type Bet struct {
	// uid is the unique uuid assigned to bet
	UID string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid"`
	// sport_event_uid is the unique uuid of te sportevent on which bet is placed
	SportEventUID string `protobuf:"bytes,2,opt,name=sport_event_uid,proto3" json:"sport_event_uid"`
	// odds_uid is the unique uuid of the odds on which bet is placed
	OddsUID string `protobuf:"bytes,3,opt,name=odds_uid,proto3" json:"odds_uid"`
	// odds_value is the odds on which bet is placed
	OddsValue github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=odds_value,json=oddsValue,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"odds_value"`
	// amount is the wagger amount deducted by betting fee
	Amount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
	// betFee is the betting fee
	BetFee types.Coin `protobuf:"bytes,6,opt,name=bet_fee,json=betFee,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"bet_fee"`
	// status is the status of the bet, such as `pending` or `settled`
	Status Bet_Status `protobuf:"varint,7,opt,name=status,proto3,enum=sgenetwork.sge.bet.Bet_Status" json:"status,omitempty"`
	// result is the result of bet, sunch as `won` or `lost`
	Result Bet_Result `protobuf:"varint,8,opt,name=result,proto3,enum=sgenetwork.sge.bet.Bet_Result" json:"result,omitempty"`
	// verified shows bet is verified or not
	Verified bool `protobuf:"varint,9,opt,name=verified,proto3" json:"verified,omitempty"`
	// ticket is a signed string containing important info such as `oddsValue`
	Ticket string `protobuf:"bytes,10,opt,name=ticket,proto3" json:"ticket,omitempty"`
	// creator is the bettor address
	Creator string `protobuf:"bytes,11,opt,name=creator,proto3" json:"creator,omitempty"`
	// created_at is bet placement timestamp
	CreatedAt int64 `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// odds_type is the type of odds used has chosen
	OddsType Bet_OddsType `protobuf:"varint,13,opt,name=odds_type,json=oddsType,proto3,enum=sgenetwork.sge.bet.Bet_OddsType" json:"odds_type,omitempty"`
}

func (m *Bet) Reset()         { *m = Bet{} }
func (m *Bet) String() string { return proto.CompactTextString(m) }
func (*Bet) ProtoMessage()    {}
func (*Bet) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bc076bb1a4d9f6e, []int{0}
}
func (m *Bet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Bet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Bet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Bet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bet.Merge(m, src)
}
func (m *Bet) XXX_Size() int {
	return m.Size()
}
func (m *Bet) XXX_DiscardUnknown() {
	xxx_messageInfo_Bet.DiscardUnknown(m)
}

var xxx_messageInfo_Bet proto.InternalMessageInfo

func (m *Bet) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *Bet) GetSportEventUID() string {
	if m != nil {
		return m.SportEventUID
	}
	return ""
}

func (m *Bet) GetOddsUID() string {
	if m != nil {
		return m.OddsUID
	}
	return ""
}

func (m *Bet) GetBetFee() types.Coin {
	if m != nil {
		return m.BetFee
	}
	return types.Coin{}
}

func (m *Bet) GetStatus() Bet_Status {
	if m != nil {
		return m.Status
	}
	return Bet_STATUS_INVALID
}

func (m *Bet) GetResult() Bet_Result {
	if m != nil {
		return m.Result
	}
	return Bet_RESULT_INVALID
}

func (m *Bet) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *Bet) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *Bet) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Bet) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Bet) GetOddsType() Bet_OddsType {
	if m != nil {
		return m.OddsType
	}
	return Bet_ODD_TYPE_INVALID
}

func init() {
	proto.RegisterEnum("sgenetwork.sge.bet.Bet_OddsType", Bet_OddsType_name, Bet_OddsType_value)
	proto.RegisterEnum("sgenetwork.sge.bet.Bet_Status", Bet_Status_name, Bet_Status_value)
	proto.RegisterEnum("sgenetwork.sge.bet.Bet_Result", Bet_Result_name, Bet_Result_value)
	proto.RegisterType((*Bet)(nil), "sgenetwork.sge.bet.Bet")
}

func init() { proto.RegisterFile("sge/bet/bet.proto", fileDescriptor_9bc076bb1a4d9f6e) }

var fileDescriptor_9bc076bb1a4d9f6e = []byte{
	// 716 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcf, 0x6e, 0xda, 0x48,
	0x18, 0xc7, 0x38, 0x31, 0x30, 0xd9, 0x10, 0x67, 0x36, 0x9b, 0x78, 0x91, 0xd6, 0x20, 0xb4, 0x6a,
	0xb9, 0xc4, 0x56, 0x12, 0xa9, 0xb7, 0x4a, 0x35, 0xd8, 0xa9, 0x2c, 0x39, 0x26, 0x1a, 0x9c, 0x44,
	0xed, 0x05, 0x61, 0xfc, 0x85, 0xa2, 0x24, 0x18, 0x31, 0x03, 0x6d, 0xde, 0xa2, 0x2f, 0xd0, 0x17,
	0xe8, 0x73, 0xf4, 0x90, 0x63, 0x8e, 0x55, 0x0f, 0xb4, 0x22, 0xb7, 0x3e, 0x45, 0x35, 0x63, 0x43,
	0x68, 0xaa, 0x56, 0xed, 0x01, 0xf8, 0xe6, 0xf7, 0xef, 0xfb, 0x3c, 0x33, 0x18, 0x6d, 0xd2, 0x1e,
	0x98, 0x21, 0x30, 0xfe, 0x31, 0x86, 0xa3, 0x98, 0xc5, 0x18, 0xd3, 0x1e, 0x0c, 0x80, 0xbd, 0x8e,
	0x47, 0x17, 0x06, 0xed, 0x81, 0x11, 0x02, 0x2b, 0x6d, 0xf5, 0xe2, 0x5e, 0x2c, 0x68, 0x93, 0x57,
	0x89, 0xb2, 0xa4, 0x77, 0x63, 0x7a, 0x15, 0x53, 0x33, 0xec, 0x50, 0x30, 0x27, 0x7b, 0x21, 0xb0,
	0xce, 0x9e, 0xd9, 0x8d, 0xfb, 0x83, 0x84, 0xaf, 0x7e, 0xc8, 0x23, 0xb9, 0x0e, 0x0c, 0x57, 0x90,
	0x3c, 0xee, 0x47, 0x9a, 0x54, 0x91, 0x6a, 0x85, 0x7a, 0x71, 0x36, 0x2d, 0xcb, 0x27, 0xae, 0xfd,
	0x75, 0x5a, 0xe6, 0x28, 0xe1, 0x5f, 0xd8, 0x47, 0x1b, 0x74, 0x18, 0x8f, 0x58, 0x1b, 0x26, 0x30,
	0x60, 0x6d, 0xae, 0xce, 0x0a, 0xf5, 0xff, 0xb3, 0x69, 0x79, 0xbd, 0xc5, 0x29, 0x87, 0x33, 0x89,
	0xef, 0xa1, 0x96, 0x3c, 0x04, 0xf0, 0x01, 0xca, 0xc7, 0x51, 0x44, 0x45, 0x90, 0x2c, 0x82, 0x76,
	0x66, 0xd3, 0x72, 0xae, 0x19, 0x45, 0x34, 0x89, 0x58, 0xd0, 0x64, 0x51, 0xe1, 0x23, 0x84, 0x44,
	0x3d, 0xe9, 0x5c, 0x8e, 0x41, 0x5b, 0x11, 0x36, 0xe3, 0x66, 0x5a, 0xce, 0x7c, 0x9a, 0x96, 0x1f,
	0xf5, 0xfa, 0xec, 0xd5, 0x38, 0x34, 0xba, 0xf1, 0x95, 0x99, 0x3e, 0x75, 0xf2, 0xb3, 0x4b, 0xa3,
	0x0b, 0x93, 0x5d, 0x0f, 0x81, 0x1a, 0x36, 0x74, 0x49, 0x81, 0x27, 0x9c, 0xf2, 0x00, 0x7c, 0x88,
	0x94, 0xce, 0x55, 0x3c, 0x1e, 0x30, 0x6d, 0xf5, 0x8f, 0xa3, 0xdc, 0x01, 0x23, 0xa9, 0x1b, 0x77,
	0x51, 0x2e, 0x04, 0xd6, 0x3e, 0x07, 0xd0, 0x94, 0x8a, 0x54, 0x5b, 0xdb, 0xff, 0xd7, 0x48, 0xf4,
	0x06, 0xdf, 0x77, 0x23, 0xdd, 0x77, 0xa3, 0x11, 0xf7, 0x07, 0x75, 0x93, 0xf7, 0x78, 0xff, 0xb9,
	0xfc, 0xf8, 0x37, 0x7a, 0x70, 0x03, 0x51, 0x42, 0x60, 0x87, 0x00, 0xf8, 0x09, 0x52, 0x28, 0xeb,
	0xb0, 0x31, 0xd5, 0x72, 0x15, 0xa9, 0x56, 0xdc, 0xd7, 0x8d, 0x1f, 0x6f, 0x81, 0x51, 0x07, 0x66,
	0xb4, 0x84, 0x8a, 0xa4, 0x6a, 0xee, 0x1b, 0x01, 0x1d, 0x5f, 0x32, 0x2d, 0xff, 0x6b, 0x1f, 0x11,
	0x2a, 0x92, 0xaa, 0x71, 0x09, 0xe5, 0x27, 0x30, 0xea, 0x9f, 0xf7, 0x21, 0xd2, 0x0a, 0x15, 0xa9,
	0x96, 0x27, 0x8b, 0x35, 0xde, 0x46, 0x0a, 0xeb, 0x77, 0x2f, 0x80, 0x69, 0x88, 0x6f, 0x1c, 0x49,
	0x57, 0x58, 0x43, 0xb9, 0xee, 0x08, 0x3a, 0x2c, 0x1e, 0x69, 0x6b, 0x82, 0x98, 0x2f, 0xf1, 0x7f,
	0x08, 0x89, 0x12, 0xa2, 0x76, 0x87, 0x69, 0x7f, 0x55, 0xa4, 0x9a, 0x4c, 0x0a, 0x29, 0x62, 0x31,
	0xfc, 0x14, 0x89, 0x63, 0x69, 0xf3, 0xe7, 0xd6, 0xd6, 0xc5, 0x9c, 0x95, 0x9f, 0xcd, 0xc9, 0xaf,
	0x48, 0x70, 0x3d, 0x84, 0xe4, 0x5e, 0xf0, 0xaa, 0x7a, 0x8e, 0xf2, 0x73, 0x14, 0x6f, 0x21, 0xb5,
	0x69, 0xdb, 0xed, 0xe0, 0xc5, 0xb1, 0xd3, 0x76, 0xfd, 0x53, 0xcb, 0x73, 0x6d, 0x35, 0xf3, 0x1d,
	0x6a, 0x3b, 0x0d, 0xf7, 0xc8, 0xf2, 0x54, 0x09, 0xef, 0xa0, 0xbf, 0x17, 0xe8, 0x21, 0xb1, 0x1a,
	0x81, 0xdb, 0xf4, 0x2d, 0x4f, 0xcd, 0xe2, 0x7f, 0xd0, 0xe6, 0x82, 0xb0, 0x8e, 0x1c, 0xe2, 0x36,
	0x2c, 0x5f, 0x95, 0xab, 0xef, 0x24, 0xa4, 0x24, 0xdb, 0x8b, 0x31, 0x2a, 0xb6, 0x02, 0x2b, 0x38,
	0x69, 0x2d, 0x35, 0xd9, 0x44, 0xeb, 0x29, 0x76, 0xec, 0x59, 0x0d, 0xc7, 0x56, 0x25, 0xde, 0x37,
	0x85, 0x1a, 0x96, 0xdf, 0x70, 0x3c, 0xcf, 0xb1, 0xd5, 0xec, 0x92, 0xd9, 0xaa, 0x37, 0x49, 0xe0,
	0xd8, 0xaa, 0xbc, 0x84, 0x1d, 0x3b, 0xbe, 0xed, 0xfa, 0xcf, 0xd5, 0x15, 0x5c, 0x42, 0xdb, 0x29,
	0x46, 0x9c, 0xd6, 0x89, 0x17, 0xf0, 0xd1, 0x3d, 0x8b, 0x38, 0xb6, 0xba, 0xba, 0xa4, 0x6f, 0x39,
	0x41, 0xc0, 0x73, 0x95, 0xea, 0x04, 0x29, 0xc9, 0x29, 0x72, 0x36, 0xb5, 0xdc, 0x8f, 0x77, 0x8f,
	0xcd, 0x3b, 0x48, 0xb8, 0x88, 0x50, 0x8a, 0x9d, 0x35, 0x7d, 0x35, 0x8b, 0x37, 0xd0, 0x5a, 0xba,
	0xf6, 0x9a, 0xad, 0x40, 0x95, 0x97, 0x00, 0x9b, 0x58, 0x67, 0xea, 0xca, 0x52, 0xca, 0x7c, 0xf6,
	0xd5, 0xfa, 0xb3, 0x9b, 0x99, 0x2e, 0xdd, 0xce, 0x74, 0xe9, 0xcb, 0x4c, 0x97, 0xde, 0xde, 0xe9,
	0x99, 0xdb, 0x3b, 0x3d, 0xf3, 0xf1, 0x4e, 0xcf, 0xbc, 0x5c, 0xfe, 0x2b, 0xd1, 0x1e, 0xec, 0xa6,
	0x07, 0xca, 0x6b, 0xf3, 0x8d, 0x78, 0xad, 0x89, 0xab, 0x1e, 0x2a, 0xe2, 0x7d, 0x74, 0xf0, 0x2d,
	0x00, 0x00, 0xff, 0xff, 0x75, 0x0f, 0x15, 0xd8, 0xee, 0x04, 0x00, 0x00,
}

func (m *Bet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Bet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Bet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OddsType != 0 {
		i = encodeVarintBet(dAtA, i, uint64(m.OddsType))
		i--
		dAtA[i] = 0x68
	}
	if m.CreatedAt != 0 {
		i = encodeVarintBet(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x60
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintBet(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.Ticket) > 0 {
		i -= len(m.Ticket)
		copy(dAtA[i:], m.Ticket)
		i = encodeVarintBet(dAtA, i, uint64(len(m.Ticket)))
		i--
		dAtA[i] = 0x52
	}
	if m.Verified {
		i--
		if m.Verified {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if m.Result != 0 {
		i = encodeVarintBet(dAtA, i, uint64(m.Result))
		i--
		dAtA[i] = 0x40
	}
	if m.Status != 0 {
		i = encodeVarintBet(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	{
		size, err := m.BetFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBet(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintBet(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.OddsValue.Size()
		i -= size
		if _, err := m.OddsValue.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintBet(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.OddsUID) > 0 {
		i -= len(m.OddsUID)
		copy(dAtA[i:], m.OddsUID)
		i = encodeVarintBet(dAtA, i, uint64(len(m.OddsUID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SportEventUID) > 0 {
		i -= len(m.SportEventUID)
		copy(dAtA[i:], m.SportEventUID)
		i = encodeVarintBet(dAtA, i, uint64(len(m.SportEventUID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.UID) > 0 {
		i -= len(m.UID)
		copy(dAtA[i:], m.UID)
		i = encodeVarintBet(dAtA, i, uint64(len(m.UID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBet(dAtA []byte, offset int, v uint64) int {
	offset -= sovBet(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Bet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UID)
	if l > 0 {
		n += 1 + l + sovBet(uint64(l))
	}
	l = len(m.SportEventUID)
	if l > 0 {
		n += 1 + l + sovBet(uint64(l))
	}
	l = len(m.OddsUID)
	if l > 0 {
		n += 1 + l + sovBet(uint64(l))
	}
	l = m.OddsValue.Size()
	n += 1 + l + sovBet(uint64(l))
	l = m.Amount.Size()
	n += 1 + l + sovBet(uint64(l))
	l = m.BetFee.Size()
	n += 1 + l + sovBet(uint64(l))
	if m.Status != 0 {
		n += 1 + sovBet(uint64(m.Status))
	}
	if m.Result != 0 {
		n += 1 + sovBet(uint64(m.Result))
	}
	if m.Verified {
		n += 2
	}
	l = len(m.Ticket)
	if l > 0 {
		n += 1 + l + sovBet(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovBet(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovBet(uint64(m.CreatedAt))
	}
	if m.OddsType != 0 {
		n += 1 + sovBet(uint64(m.OddsType))
	}
	return n
}

func sovBet(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBet(x uint64) (n int) {
	return sovBet(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Bet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Bet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Bet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SportEventUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SportEventUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OddsUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OddsUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OddsValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OddsValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BetFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BetFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Bet_Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			m.Result = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Result |= Bet_Result(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verified", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Verified = bool(v != 0)
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ticket", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ticket = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OddsType", wireType)
			}
			m.OddsType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OddsType |= Bet_OddsType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBet(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBet
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBet
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBet
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBet
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBet        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBet          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBet = fmt.Errorf("proto: unexpected end of group")
)
