// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sge/reward/reward.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RewardType defines supported types of rewards of reward module.
type RewardType int32

const (
	// the invalid or unknown
	RewardType_REWARD_TYPE_UNSPECIFIED RewardType = 0
	RewardType_REWARD_TYPE_SIGNUP      RewardType = 1
	RewardType_REWARD_TYPE_REFERRAL    RewardType = 2
	RewardType_REWARD_TYPE_AFFILIATION RewardType = 3
	RewardType_REWARD_TYPE_NOLOSS_BETS RewardType = 4
)

var RewardType_name = map[int32]string{
	0: "REWARD_TYPE_UNSPECIFIED",
	1: "REWARD_TYPE_SIGNUP",
	2: "REWARD_TYPE_REFERRAL",
	3: "REWARD_TYPE_AFFILIATION",
	4: "REWARD_TYPE_NOLOSS_BETS",
}

var RewardType_value = map[string]int32{
	"REWARD_TYPE_UNSPECIFIED": 0,
	"REWARD_TYPE_SIGNUP":      1,
	"REWARD_TYPE_REFERRAL":    2,
	"REWARD_TYPE_AFFILIATION": 3,
	"REWARD_TYPE_NOLOSS_BETS": 4,
}

func (x RewardType) String() string {
	return proto.EnumName(RewardType_name, int32(x))
}

func (RewardType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3412add70a4f177f, []int{0}
}

// ReceiverAccType defines supported types account types for reward
// distribution.
type ReceiverAccType int32

const (
	// the invalid or unknown
	ReceiverAccType_RECEIVER_ACC_TYPE_UNSPECIFIED ReceiverAccType = 0
	ReceiverAccType_RECEIVER_ACC_TYPE_MAIN        ReceiverAccType = 1
	ReceiverAccType_RECEIVER_ACC_TYPE_SUB         ReceiverAccType = 2
)

var ReceiverAccType_name = map[int32]string{
	0: "RECEIVER_ACC_TYPE_UNSPECIFIED",
	1: "RECEIVER_ACC_TYPE_MAIN",
	2: "RECEIVER_ACC_TYPE_SUB",
}

var ReceiverAccType_value = map[string]int32{
	"RECEIVER_ACC_TYPE_UNSPECIFIED": 0,
	"RECEIVER_ACC_TYPE_MAIN":        1,
	"RECEIVER_ACC_TYPE_SUB":         2,
}

func (x ReceiverAccType) String() string {
	return proto.EnumName(ReceiverAccType_name, int32(x))
}

func (ReceiverAccType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3412add70a4f177f, []int{1}
}

// ReceiverType defines all of reward receiver types in the system.
type ReceiverType int32

const (
	// the invalid or unknown
	ReceiverType_RECEIVER_TYPE_UNSPECIFIED ReceiverType = 0
	ReceiverType_RECEIVER_TYPE_SINGLE      ReceiverType = 1
	ReceiverType_RECEIVER_TYPE_REFERRER    ReceiverType = 2
	ReceiverType_RECEIVER_TYPE_REFEREE     ReceiverType = 3
)

var ReceiverType_name = map[int32]string{
	0: "RECEIVER_TYPE_UNSPECIFIED",
	1: "RECEIVER_TYPE_SINGLE",
	2: "RECEIVER_TYPE_REFERRER",
	3: "RECEIVER_TYPE_REFEREE",
}

var ReceiverType_value = map[string]int32{
	"RECEIVER_TYPE_UNSPECIFIED": 0,
	"RECEIVER_TYPE_SINGLE":      1,
	"RECEIVER_TYPE_REFERRER":    2,
	"RECEIVER_TYPE_REFEREE":     3,
}

func (x ReceiverType) String() string {
	return proto.EnumName(ReceiverType_name, int32(x))
}

func (ReceiverType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3412add70a4f177f, []int{2}
}

type RewardCommon struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	CampaignUID string `protobuf:"bytes,2,opt,name=campaign_uid,proto3" json:"campaign_uid"`
	TS          uint64 `protobuf:"varint,3,opt,name=ts,proto3" json:"ts"`
}

func (m *RewardCommon) Reset()         { *m = RewardCommon{} }
func (m *RewardCommon) String() string { return proto.CompactTextString(m) }
func (*RewardCommon) ProtoMessage()    {}
func (*RewardCommon) Descriptor() ([]byte, []int) {
	return fileDescriptor_3412add70a4f177f, []int{0}
}
func (m *RewardCommon) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RewardCommon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RewardCommon.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RewardCommon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardCommon.Merge(m, src)
}
func (m *RewardCommon) XXX_Size() int {
	return m.Size()
}
func (m *RewardCommon) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardCommon.DiscardUnknown(m)
}

var xxx_messageInfo_RewardCommon proto.InternalMessageInfo

func (m *RewardCommon) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *RewardCommon) GetCampaignUID() string {
	if m != nil {
		return m.CampaignUID
	}
	return ""
}

func (m *RewardCommon) GetTS() uint64 {
	if m != nil {
		return m.TS
	}
	return 0
}

// Definition is the type for reward declaration for a campaign.
type Definition struct {
	Type        ReceiverType                           `protobuf:"varint,1,opt,name=type,proto3,enum=sgenetwork.sge.reward.ReceiverType" json:"type,omitempty"`
	Amount      github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount" yaml:"amount"`
	DstAccType  ReceiverAccType                        `protobuf:"varint,3,opt,name=dst_acc_type,json=dstAccType,proto3,enum=sgenetwork.sge.reward.ReceiverAccType" json:"dst_acc_type,omitempty"`
	ExpDuration uint64                                 `protobuf:"varint,4,opt,name=exp_duration,json=expDuration,proto3" json:"exp_duration,omitempty"`
}

func (m *Definition) Reset()         { *m = Definition{} }
func (m *Definition) String() string { return proto.CompactTextString(m) }
func (*Definition) ProtoMessage()    {}
func (*Definition) Descriptor() ([]byte, []int) {
	return fileDescriptor_3412add70a4f177f, []int{1}
}
func (m *Definition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Definition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Definition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Definition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Definition.Merge(m, src)
}
func (m *Definition) XXX_Size() int {
	return m.Size()
}
func (m *Definition) XXX_DiscardUnknown() {
	xxx_messageInfo_Definition.DiscardUnknown(m)
}

var xxx_messageInfo_Definition proto.InternalMessageInfo

func (m *Definition) GetType() ReceiverType {
	if m != nil {
		return m.Type
	}
	return ReceiverType_RECEIVER_TYPE_UNSPECIFIED
}

func (m *Definition) GetDstAccType() ReceiverAccType {
	if m != nil {
		return m.DstAccType
	}
	return ReceiverAccType_RECEIVER_ACC_TYPE_UNSPECIFIED
}

func (m *Definition) GetExpDuration() uint64 {
	if m != nil {
		return m.ExpDuration
	}
	return 0
}

// Distribution is the type for the distribution of a reward.
type Distribution struct {
	AccAddr    string     `protobuf:"bytes,1,opt,name=acc_addr,json=accAddr,proto3" json:"acc_addr,omitempty"`
	Allocation Allocation `protobuf:"bytes,2,opt,name=allocation,proto3" json:"allocation"`
}

func (m *Distribution) Reset()         { *m = Distribution{} }
func (m *Distribution) String() string { return proto.CompactTextString(m) }
func (*Distribution) ProtoMessage()    {}
func (*Distribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_3412add70a4f177f, []int{2}
}
func (m *Distribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Distribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Distribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Distribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Distribution.Merge(m, src)
}
func (m *Distribution) XXX_Size() int {
	return m.Size()
}
func (m *Distribution) XXX_DiscardUnknown() {
	xxx_messageInfo_Distribution.DiscardUnknown(m)
}

var xxx_messageInfo_Distribution proto.InternalMessageInfo

func (m *Distribution) GetAccAddr() string {
	if m != nil {
		return m.AccAddr
	}
	return ""
}

func (m *Distribution) GetAllocation() Allocation {
	if m != nil {
		return m.Allocation
	}
	return Allocation{}
}

// Allocation is the distribution allocation of the rewards.
type Allocation struct {
	Amount          github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount" yaml:"amount"`
	ReceiverAccType ReceiverAccType                        `protobuf:"varint,2,opt,name=receiver_acc_type,json=receiverAccType,proto3,enum=sgenetwork.sge.reward.ReceiverAccType" json:"receiver_acc_type,omitempty"`
	ExpTs           uint64                                 `protobuf:"varint,3,opt,name=exp_ts,json=expTs,proto3" json:"exp_ts,omitempty"`
}

func (m *Allocation) Reset()         { *m = Allocation{} }
func (m *Allocation) String() string { return proto.CompactTextString(m) }
func (*Allocation) ProtoMessage()    {}
func (*Allocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3412add70a4f177f, []int{3}
}
func (m *Allocation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Allocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Allocation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Allocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Allocation.Merge(m, src)
}
func (m *Allocation) XXX_Size() int {
	return m.Size()
}
func (m *Allocation) XXX_DiscardUnknown() {
	xxx_messageInfo_Allocation.DiscardUnknown(m)
}

var xxx_messageInfo_Allocation proto.InternalMessageInfo

func (m *Allocation) GetReceiverAccType() ReceiverAccType {
	if m != nil {
		return m.ReceiverAccType
	}
	return ReceiverAccType_RECEIVER_ACC_TYPE_UNSPECIFIED
}

func (m *Allocation) GetExpTs() uint64 {
	if m != nil {
		return m.ExpTs
	}
	return 0
}

// Receiver is the type for reward receiver properties.
type Receiver struct {
	RecType ReceiverType `protobuf:"varint,1,opt,name=rec_type,json=recType,proto3,enum=sgenetwork.sge.reward.ReceiverType" json:"rec_type,omitempty"`
	Addr    string       `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (m *Receiver) Reset()         { *m = Receiver{} }
func (m *Receiver) String() string { return proto.CompactTextString(m) }
func (*Receiver) ProtoMessage()    {}
func (*Receiver) Descriptor() ([]byte, []int) {
	return fileDescriptor_3412add70a4f177f, []int{4}
}
func (m *Receiver) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Receiver) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Receiver.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Receiver) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receiver.Merge(m, src)
}
func (m *Receiver) XXX_Size() int {
	return m.Size()
}
func (m *Receiver) XXX_DiscardUnknown() {
	xxx_messageInfo_Receiver.DiscardUnknown(m)
}

var xxx_messageInfo_Receiver proto.InternalMessageInfo

func (m *Receiver) GetRecType() ReceiverType {
	if m != nil {
		return m.RecType
	}
	return ReceiverType_RECEIVER_TYPE_UNSPECIFIED
}

func (m *Receiver) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func init() {
	proto.RegisterEnum("sgenetwork.sge.reward.RewardType", RewardType_name, RewardType_value)
	proto.RegisterEnum("sgenetwork.sge.reward.ReceiverAccType", ReceiverAccType_name, ReceiverAccType_value)
	proto.RegisterEnum("sgenetwork.sge.reward.ReceiverType", ReceiverType_name, ReceiverType_value)
	proto.RegisterType((*RewardCommon)(nil), "sgenetwork.sge.reward.RewardCommon")
	proto.RegisterType((*Definition)(nil), "sgenetwork.sge.reward.Definition")
	proto.RegisterType((*Distribution)(nil), "sgenetwork.sge.reward.Distribution")
	proto.RegisterType((*Allocation)(nil), "sgenetwork.sge.reward.Allocation")
	proto.RegisterType((*Receiver)(nil), "sgenetwork.sge.reward.Receiver")
}

func init() { proto.RegisterFile("sge/reward/reward.proto", fileDescriptor_3412add70a4f177f) }

var fileDescriptor_3412add70a4f177f = []byte{
	// 696 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4f, 0x4f, 0xdb, 0x4a,
	0x10, 0x8f, 0x9d, 0x3c, 0xe0, 0x0d, 0x79, 0x0f, 0x77, 0xc5, 0x9f, 0x40, 0x4b, 0x0c, 0xa9, 0x84,
	0x28, 0x12, 0x89, 0x44, 0x0f, 0x95, 0x7a, 0x68, 0xe5, 0x38, 0x0e, 0xb5, 0x94, 0x06, 0xb4, 0x4e,
	0x8a, 0xda, 0x43, 0x2d, 0x63, 0x6f, 0x5d, 0x0b, 0x12, 0x47, 0xbb, 0x9b, 0x12, 0x2e, 0xfd, 0x02,
	0x5c, 0x7a, 0xe9, 0x77, 0xe2, 0xc8, 0xb1, 0xea, 0x21, 0xaa, 0xc2, 0x8d, 0x63, 0x3f, 0x41, 0xe5,
	0x8d, 0x43, 0x1c, 0xa0, 0xaa, 0x90, 0x7a, 0xf2, 0xec, 0xcc, 0x6f, 0x66, 0x7e, 0xf3, 0xdb, 0xf1,
	0xc2, 0x12, 0xf3, 0x49, 0x89, 0x92, 0x13, 0x87, 0x7a, 0xf1, 0xa7, 0xd8, 0xa1, 0x21, 0x0f, 0xd1,
	0x02, 0xf3, 0x49, 0x9b, 0xf0, 0x93, 0x90, 0x1e, 0x15, 0x99, 0x4f, 0x8a, 0xc3, 0xe0, 0xca, 0xbc,
	0x1f, 0xfa, 0xa1, 0x40, 0x94, 0x22, 0x6b, 0x08, 0x2e, 0x9c, 0x49, 0x90, 0xc5, 0x02, 0xa0, 0x87,
	0xad, 0x56, 0xd8, 0x46, 0x39, 0x98, 0x76, 0x29, 0x71, 0x78, 0x48, 0x73, 0xd2, 0x9a, 0xb4, 0xf9,
	0x2f, 0x1e, 0x1d, 0x91, 0x0e, 0x59, 0xd7, 0x69, 0x75, 0x9c, 0xc0, 0x6f, 0xdb, 0xdd, 0xc0, 0xcb,
	0xc9, 0x51, 0xb8, 0xac, 0x0e, 0xfa, 0xea, 0xac, 0x1e, 0xfb, 0x9b, 0x66, 0xe5, 0xaa, 0xaf, 0x4e,
	0xc0, 0xf0, 0xc4, 0x09, 0x3d, 0x02, 0x99, 0xb3, 0x5c, 0x7a, 0x4d, 0xda, 0xcc, 0x94, 0xb3, 0x83,
	0xbe, 0x2a, 0x37, 0xac, 0xab, 0xbe, 0x2a, 0x73, 0x86, 0x65, 0xce, 0x0a, 0x67, 0x32, 0x40, 0x85,
	0x7c, 0x08, 0xda, 0x01, 0x0f, 0xc2, 0x36, 0x7a, 0x06, 0x19, 0x7e, 0xda, 0x21, 0x82, 0xc8, 0xff,
	0x3b, 0x8f, 0x8b, 0x77, 0x0e, 0x56, 0xc4, 0xc4, 0x25, 0xc1, 0x27, 0x42, 0x1b, 0xa7, 0x1d, 0x82,
	0x45, 0x02, 0x3a, 0x80, 0x29, 0xa7, 0x15, 0x76, 0xdb, 0x3c, 0x26, 0xf9, 0xf2, 0xbc, 0xaf, 0xa6,
	0xbe, 0xf7, 0xd5, 0x0d, 0x3f, 0xe0, 0x1f, 0xbb, 0x87, 0x45, 0x37, 0x6c, 0x95, 0xdc, 0x90, 0xb5,
	0x42, 0x16, 0x7f, 0xb6, 0x99, 0x77, 0x54, 0x8a, 0x52, 0x59, 0xd1, 0x6c, 0xf3, 0x9f, 0x7d, 0xf5,
	0xbf, 0x53, 0xa7, 0x75, 0xfc, 0xbc, 0x30, 0xac, 0x52, 0xc0, 0x71, 0x39, 0xf4, 0x0a, 0xb2, 0x1e,
	0xe3, 0xb6, 0xe3, 0xba, 0xb6, 0x60, 0x96, 0x16, 0xcc, 0x36, 0xfe, 0xc0, 0x4c, 0x73, 0x5d, 0x41,
	0x0e, 0x3c, 0xc6, 0x63, 0x1b, 0xad, 0x43, 0x96, 0xf4, 0x3a, 0xb6, 0xd7, 0xa5, 0x4e, 0x34, 0x6b,
	0x2e, 0x13, 0x49, 0x82, 0x67, 0x49, 0xaf, 0x53, 0x89, 0x5d, 0x05, 0x0a, 0xd9, 0x4a, 0xc0, 0x38,
	0x0d, 0x0e, 0xbb, 0x42, 0x8e, 0x65, 0x98, 0x89, 0x1a, 0x3b, 0x9e, 0x77, 0x7d, 0x37, 0x8e, 0xeb,
	0x6a, 0x9e, 0x47, 0xd1, 0x2e, 0x80, 0x73, 0x7c, 0x1c, 0xba, 0xc3, 0x5a, 0xd1, 0xd0, 0xb3, 0x3b,
	0xeb, 0xbf, 0x61, 0xa5, 0x5d, 0x03, 0xcb, 0x99, 0x48, 0x17, 0x9c, 0x48, 0x2d, 0x5c, 0x48, 0x00,
	0x63, 0x40, 0x42, 0x48, 0xe9, 0xef, 0x0a, 0x89, 0xe1, 0x01, 0x8d, 0xd5, 0x19, 0xab, 0x29, 0xdf,
	0x4b, 0xcd, 0x39, 0x3a, 0xe9, 0x40, 0x0b, 0x30, 0x15, 0x49, 0x3a, 0xda, 0x2f, 0xfc, 0x0f, 0xe9,
	0x75, 0x1a, 0xac, 0xf0, 0x1e, 0x66, 0x46, 0xa9, 0xe8, 0x05, 0xcc, 0x50, 0x12, 0x77, 0xbb, 0xc7,
	0x56, 0x4d, 0x53, 0x32, 0x6c, 0x81, 0x20, 0x23, 0xe4, 0x17, 0x6b, 0x85, 0x85, 0xbd, 0xf5, 0x55,
	0x02, 0x18, 0xfe, 0x42, 0x02, 0xf2, 0x10, 0x96, 0xb0, 0x71, 0xa0, 0xe1, 0x8a, 0xdd, 0x78, 0xbb,
	0x6f, 0xd8, 0xcd, 0xba, 0xb5, 0x6f, 0xe8, 0x66, 0xd5, 0x34, 0x2a, 0x4a, 0x0a, 0x2d, 0x02, 0x4a,
	0x06, 0x2d, 0x73, 0xb7, 0xde, 0xdc, 0x57, 0x24, 0x94, 0x83, 0xf9, 0xa4, 0x1f, 0x1b, 0x55, 0x03,
	0x63, 0xad, 0xa6, 0xc8, 0x37, 0xcb, 0x69, 0xd5, 0xaa, 0x59, 0x33, 0xb5, 0x86, 0xb9, 0x57, 0x57,
	0xd2, 0x37, 0x83, 0xf5, 0xbd, 0xda, 0x9e, 0x65, 0xd9, 0x65, 0xa3, 0x61, 0x29, 0x99, 0xad, 0x23,
	0x98, 0xbb, 0x21, 0x19, 0x5a, 0x87, 0x55, 0x6c, 0xe8, 0x86, 0xf9, 0xc6, 0xc0, 0xb6, 0xa6, 0xeb,
	0x77, 0x31, 0x5c, 0x81, 0xc5, 0xdb, 0x90, 0xd7, 0x9a, 0x59, 0x57, 0x24, 0xb4, 0x0c, 0x0b, 0xb7,
	0x63, 0x56, 0xb3, 0xac, 0xc8, 0x5b, 0x9f, 0xa3, 0x67, 0x64, 0xac, 0x18, 0x5a, 0x85, 0xe5, 0x6b,
	0xe8, 0x1d, 0x5d, 0xc4, 0xbc, 0xc9, 0xb0, 0x65, 0xd6, 0x77, 0x6b, 0x86, 0x22, 0x4d, 0xf4, 0x4f,
	0x68, 0x61, 0x60, 0x45, 0x9e, 0xe8, 0x3f, 0x8e, 0x19, 0x86, 0x92, 0x2e, 0xeb, 0xe7, 0x83, 0xbc,
	0x74, 0x31, 0xc8, 0x4b, 0x3f, 0x06, 0x79, 0xe9, 0xcb, 0x65, 0x3e, 0x75, 0x71, 0x99, 0x4f, 0x7d,
	0xbb, 0xcc, 0xa7, 0xde, 0x3d, 0x49, 0xac, 0x2a, 0xf3, 0xc9, 0x76, 0x7c, 0xd7, 0x91, 0x5d, 0xea,
	0x8d, 0x1e, 0x50, 0xb1, 0xb1, 0x87, 0x53, 0xe2, 0x4d, 0x7c, 0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff,
	0x38, 0x41, 0x69, 0x30, 0x5b, 0x05, 0x00, 0x00,
}

func (m *RewardCommon) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RewardCommon) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RewardCommon) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TS != 0 {
		i = encodeVarintReward(dAtA, i, uint64(m.TS))
		i--
		dAtA[i] = 0x18
	}
	if len(m.CampaignUID) > 0 {
		i -= len(m.CampaignUID)
		copy(dAtA[i:], m.CampaignUID)
		i = encodeVarintReward(dAtA, i, uint64(len(m.CampaignUID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintReward(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Definition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Definition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Definition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpDuration != 0 {
		i = encodeVarintReward(dAtA, i, uint64(m.ExpDuration))
		i--
		dAtA[i] = 0x20
	}
	if m.DstAccType != 0 {
		i = encodeVarintReward(dAtA, i, uint64(m.DstAccType))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintReward(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Type != 0 {
		i = encodeVarintReward(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Distribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Distribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Distribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Allocation.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintReward(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.AccAddr) > 0 {
		i -= len(m.AccAddr)
		copy(dAtA[i:], m.AccAddr)
		i = encodeVarintReward(dAtA, i, uint64(len(m.AccAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Allocation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Allocation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Allocation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpTs != 0 {
		i = encodeVarintReward(dAtA, i, uint64(m.ExpTs))
		i--
		dAtA[i] = 0x18
	}
	if m.ReceiverAccType != 0 {
		i = encodeVarintReward(dAtA, i, uint64(m.ReceiverAccType))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintReward(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Receiver) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Receiver) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Receiver) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintReward(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0x12
	}
	if m.RecType != 0 {
		i = encodeVarintReward(dAtA, i, uint64(m.RecType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintReward(dAtA []byte, offset int, v uint64) int {
	offset -= sovReward(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RewardCommon) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovReward(uint64(l))
	}
	l = len(m.CampaignUID)
	if l > 0 {
		n += 1 + l + sovReward(uint64(l))
	}
	if m.TS != 0 {
		n += 1 + sovReward(uint64(m.TS))
	}
	return n
}

func (m *Definition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovReward(uint64(m.Type))
	}
	l = m.Amount.Size()
	n += 1 + l + sovReward(uint64(l))
	if m.DstAccType != 0 {
		n += 1 + sovReward(uint64(m.DstAccType))
	}
	if m.ExpDuration != 0 {
		n += 1 + sovReward(uint64(m.ExpDuration))
	}
	return n
}

func (m *Distribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccAddr)
	if l > 0 {
		n += 1 + l + sovReward(uint64(l))
	}
	l = m.Allocation.Size()
	n += 1 + l + sovReward(uint64(l))
	return n
}

func (m *Allocation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Amount.Size()
	n += 1 + l + sovReward(uint64(l))
	if m.ReceiverAccType != 0 {
		n += 1 + sovReward(uint64(m.ReceiverAccType))
	}
	if m.ExpTs != 0 {
		n += 1 + sovReward(uint64(m.ExpTs))
	}
	return n
}

func (m *Receiver) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RecType != 0 {
		n += 1 + sovReward(uint64(m.RecType))
	}
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovReward(uint64(l))
	}
	return n
}

func sovReward(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozReward(x uint64) (n int) {
	return sovReward(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RewardCommon) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReward
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RewardCommon: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RewardCommon: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReward
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReward
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReward
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CampaignUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReward
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReward
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReward
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CampaignUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TS", wireType)
			}
			m.TS = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReward
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TS |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipReward(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReward
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Definition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReward
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Definition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Definition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReward
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= ReceiverType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReward
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReward
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReward
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DstAccType", wireType)
			}
			m.DstAccType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReward
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DstAccType |= ReceiverAccType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpDuration", wireType)
			}
			m.ExpDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReward
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpDuration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipReward(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReward
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Distribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReward
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Distribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Distribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReward
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReward
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReward
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Allocation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReward
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthReward
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthReward
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Allocation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReward(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReward
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Allocation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReward
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Allocation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Allocation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReward
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReward
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReward
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiverAccType", wireType)
			}
			m.ReceiverAccType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReward
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReceiverAccType |= ReceiverAccType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpTs", wireType)
			}
			m.ExpTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReward
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpTs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipReward(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReward
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Receiver) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowReward
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Receiver: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Receiver: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecType", wireType)
			}
			m.RecType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReward
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecType |= ReceiverType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowReward
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthReward
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthReward
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipReward(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthReward
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipReward(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowReward
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReward
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowReward
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthReward
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupReward
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthReward
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthReward        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowReward          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupReward = fmt.Errorf("proto: unexpected end of group")
)
