// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sgenetwork/sge/mint/query.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method.
// Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee35ae03c8ab12c8, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
// Query/Params RPC method.
type QueryParamsResponse struct {
	// params contains all of the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee35ae03c8ab12c8, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryInflationRequest is the request type for the Query/Inflation RPC method.
// Query/Inflation RPC method.
type QueryInflationRequest struct {
}

func (m *QueryInflationRequest) Reset()         { *m = QueryInflationRequest{} }
func (m *QueryInflationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInflationRequest) ProtoMessage()    {}
func (*QueryInflationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee35ae03c8ab12c8, []int{2}
}
func (m *QueryInflationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInflationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInflationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInflationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInflationRequest.Merge(m, src)
}
func (m *QueryInflationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryInflationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInflationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInflationRequest proto.InternalMessageInfo

// QueryInflationResponse is the response type for the Query/Inflation RPC
// method.
// Query/Inflation RPC method.
type QueryInflationResponse struct {
	// inflation is the current minting inflation value.
	Inflation cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=inflation,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"inflation"`
}

func (m *QueryInflationResponse) Reset()         { *m = QueryInflationResponse{} }
func (m *QueryInflationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInflationResponse) ProtoMessage()    {}
func (*QueryInflationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee35ae03c8ab12c8, []int{3}
}
func (m *QueryInflationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInflationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInflationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInflationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInflationResponse.Merge(m, src)
}
func (m *QueryInflationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInflationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInflationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInflationResponse proto.InternalMessageInfo

// QueryPhaseStepRequest is the request type for the Query/Inflation RPC method.
// Query/PhaseStep RPC method.
type QueryPhaseStepRequest struct {
}

func (m *QueryPhaseStepRequest) Reset()         { *m = QueryPhaseStepRequest{} }
func (m *QueryPhaseStepRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPhaseStepRequest) ProtoMessage()    {}
func (*QueryPhaseStepRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee35ae03c8ab12c8, []int{4}
}
func (m *QueryPhaseStepRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPhaseStepRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPhaseStepRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPhaseStepRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPhaseStepRequest.Merge(m, src)
}
func (m *QueryPhaseStepRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPhaseStepRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPhaseStepRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPhaseStepRequest proto.InternalMessageInfo

// QueryPhaseStepResponse is the response type for the Query/Inflation RPC
// method.
// Query/PhaseStep RPC method.
type QueryPhaseStepResponse struct {
	// phase_step is the current phase number of the blockchain.
	PhaseStep int32 `protobuf:"varint,1,opt,name=phase_step,json=phaseStep,proto3" json:"phase_step,omitempty"`
}

func (m *QueryPhaseStepResponse) Reset()         { *m = QueryPhaseStepResponse{} }
func (m *QueryPhaseStepResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPhaseStepResponse) ProtoMessage()    {}
func (*QueryPhaseStepResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee35ae03c8ab12c8, []int{5}
}
func (m *QueryPhaseStepResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPhaseStepResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPhaseStepResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPhaseStepResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPhaseStepResponse.Merge(m, src)
}
func (m *QueryPhaseStepResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPhaseStepResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPhaseStepResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPhaseStepResponse proto.InternalMessageInfo

func (m *QueryPhaseStepResponse) GetPhaseStep() int32 {
	if m != nil {
		return m.PhaseStep
	}
	return 0
}

// QueryPhaseProvisionsRequest is the request type for the
// Query/PhaseProvisions RPC method.
type QueryPhaseProvisionsRequest struct {
}

func (m *QueryPhaseProvisionsRequest) Reset()         { *m = QueryPhaseProvisionsRequest{} }
func (m *QueryPhaseProvisionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPhaseProvisionsRequest) ProtoMessage()    {}
func (*QueryPhaseProvisionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee35ae03c8ab12c8, []int{6}
}
func (m *QueryPhaseProvisionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPhaseProvisionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPhaseProvisionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPhaseProvisionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPhaseProvisionsRequest.Merge(m, src)
}
func (m *QueryPhaseProvisionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPhaseProvisionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPhaseProvisionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPhaseProvisionsRequest proto.InternalMessageInfo

// QueryPhaseProvisionsResponse is the response type for the
// Query/PhaseProvisions RPC method.
type QueryPhaseProvisionsResponse struct {
	// phase_provisions is the current minting phase provisions value.
	PhaseProvisions cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=phase_provisions,json=phaseProvisions,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"phase_provisions"`
}

func (m *QueryPhaseProvisionsResponse) Reset()         { *m = QueryPhaseProvisionsResponse{} }
func (m *QueryPhaseProvisionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPhaseProvisionsResponse) ProtoMessage()    {}
func (*QueryPhaseProvisionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee35ae03c8ab12c8, []int{7}
}
func (m *QueryPhaseProvisionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPhaseProvisionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPhaseProvisionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPhaseProvisionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPhaseProvisionsResponse.Merge(m, src)
}
func (m *QueryPhaseProvisionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPhaseProvisionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPhaseProvisionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPhaseProvisionsResponse proto.InternalMessageInfo

// QueryEndPhaseStatusRequest is the request type for the Query/Inflation RPC
// method.
// Query/EndPhaseStatus RPC method.
type QueryEndPhaseStatusRequest struct {
}

func (m *QueryEndPhaseStatusRequest) Reset()         { *m = QueryEndPhaseStatusRequest{} }
func (m *QueryEndPhaseStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEndPhaseStatusRequest) ProtoMessage()    {}
func (*QueryEndPhaseStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee35ae03c8ab12c8, []int{8}
}
func (m *QueryEndPhaseStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEndPhaseStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEndPhaseStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEndPhaseStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEndPhaseStatusRequest.Merge(m, src)
}
func (m *QueryEndPhaseStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEndPhaseStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEndPhaseStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEndPhaseStatusRequest proto.InternalMessageInfo

// QueryEndPhaseStatusResponse is the response type for the Query/Inflation RPC
// method.
// Query/EndPhaseStatus RPC method.
type QueryEndPhaseStatusResponse struct {
	// is_in_end_phase is true if there is no more valid phase in the mint
	// parameters.
	IsInEndPhase bool `protobuf:"varint,1,opt,name=is_in_end_phase,json=isInEndPhase,proto3" json:"is_in_end_phase,omitempty"`
}

func (m *QueryEndPhaseStatusResponse) Reset()         { *m = QueryEndPhaseStatusResponse{} }
func (m *QueryEndPhaseStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEndPhaseStatusResponse) ProtoMessage()    {}
func (*QueryEndPhaseStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee35ae03c8ab12c8, []int{9}
}
func (m *QueryEndPhaseStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEndPhaseStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEndPhaseStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEndPhaseStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEndPhaseStatusResponse.Merge(m, src)
}
func (m *QueryEndPhaseStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEndPhaseStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEndPhaseStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEndPhaseStatusResponse proto.InternalMessageInfo

func (m *QueryEndPhaseStatusResponse) GetIsInEndPhase() bool {
	if m != nil {
		return m.IsInEndPhase
	}
	return false
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "sgenetwork.sge.mint.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "sgenetwork.sge.mint.QueryParamsResponse")
	proto.RegisterType((*QueryInflationRequest)(nil), "sgenetwork.sge.mint.QueryInflationRequest")
	proto.RegisterType((*QueryInflationResponse)(nil), "sgenetwork.sge.mint.QueryInflationResponse")
	proto.RegisterType((*QueryPhaseStepRequest)(nil), "sgenetwork.sge.mint.QueryPhaseStepRequest")
	proto.RegisterType((*QueryPhaseStepResponse)(nil), "sgenetwork.sge.mint.QueryPhaseStepResponse")
	proto.RegisterType((*QueryPhaseProvisionsRequest)(nil), "sgenetwork.sge.mint.QueryPhaseProvisionsRequest")
	proto.RegisterType((*QueryPhaseProvisionsResponse)(nil), "sgenetwork.sge.mint.QueryPhaseProvisionsResponse")
	proto.RegisterType((*QueryEndPhaseStatusRequest)(nil), "sgenetwork.sge.mint.QueryEndPhaseStatusRequest")
	proto.RegisterType((*QueryEndPhaseStatusResponse)(nil), "sgenetwork.sge.mint.QueryEndPhaseStatusResponse")
}

func init() { proto.RegisterFile("sgenetwork/sge/mint/query.proto", fileDescriptor_ee35ae03c8ab12c8) }

var fileDescriptor_ee35ae03c8ab12c8 = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x63, 0xa4, 0x56, 0xe4, 0xa8, 0x48, 0xb9, 0x16, 0x28, 0x4e, 0xea, 0x44, 0x16, 0x6d,
	0xaa, 0x42, 0xec, 0xa6, 0x48, 0xb0, 0x21, 0x11, 0x85, 0xa1, 0x12, 0x43, 0x08, 0xb0, 0xb0, 0x44,
	0x97, 0xe4, 0x70, 0xac, 0xd6, 0x77, 0x6e, 0xee, 0x52, 0xc8, 0x08, 0x33, 0x03, 0x12, 0x9f, 0x80,
	0x01, 0x89, 0x91, 0x81, 0x0f, 0xd1, 0xb1, 0x82, 0x05, 0x31, 0x54, 0x28, 0x41, 0x82, 0x8f, 0x81,
	0x7c, 0x77, 0x76, 0x12, 0xc7, 0x69, 0x8a, 0x58, 0xaa, 0xfa, 0xbd, 0xf7, 0xff, 0xbf, 0xdf, 0xd9,
	0xff, 0x1c, 0xc8, 0x33, 0x07, 0x13, 0xcc, 0x5f, 0xd2, 0xee, 0xbe, 0xcd, 0x1c, 0x6c, 0x7b, 0x2e,
	0xe1, 0xf6, 0x61, 0x0f, 0x77, 0xfb, 0x96, 0xdf, 0xa5, 0x9c, 0xc2, 0x95, 0xd1, 0x80, 0xc5, 0x1c,
	0x6c, 0x05, 0x03, 0xfa, 0x15, 0xe4, 0xb9, 0x84, 0xda, 0xe2, 0xaf, 0x9c, 0xd3, 0x6f, 0xb4, 0x28,
	0xf3, 0x28, 0x6b, 0x88, 0x27, 0x5b, 0x3e, 0xa8, 0xd6, 0xaa, 0x43, 0x1d, 0x2a, 0xeb, 0xc1, 0x7f,
	0xaa, 0x9a, 0x73, 0x28, 0x75, 0x0e, 0xb0, 0x8d, 0x7c, 0xd7, 0x46, 0x84, 0x50, 0x8e, 0xb8, 0x4b,
	0x49, 0xa8, 0x29, 0x24, 0x71, 0xf9, 0xa8, 0x8b, 0x3c, 0x35, 0x61, 0xae, 0x02, 0xf8, 0x38, 0xe0,
	0xac, 0x89, 0x62, 0x1d, 0x1f, 0xf6, 0x30, 0xe3, 0xe6, 0x33, 0xb0, 0x32, 0x51, 0x65, 0x3e, 0x25,
	0x0c, 0xc3, 0xfb, 0x60, 0x51, 0x8a, 0xd7, 0xb4, 0x82, 0xb6, 0x75, 0x69, 0x37, 0x6b, 0x25, 0x1c,
	0xcb, 0x92, 0xa2, 0x4a, 0xfa, 0xf8, 0x34, 0x9f, 0xfa, 0xf4, 0xfb, 0xf3, 0xb6, 0x56, 0x57, 0x2a,
	0xf3, 0x3a, 0xb8, 0x2a, 0x6c, 0xf7, 0xc8, 0x8b, 0x03, 0xc1, 0x19, 0xee, 0x23, 0xe0, 0x5a, 0xbc,
	0xa1, 0x56, 0x3e, 0x05, 0x69, 0x37, 0x2c, 0x8a, 0xad, 0x4b, 0x95, 0xbb, 0x81, 0xf1, 0x8f, 0xd3,
	0x7c, 0x56, 0xbe, 0x1e, 0xd6, 0xde, 0xb7, 0x5c, 0x6a, 0x7b, 0x88, 0x77, 0xac, 0x47, 0xd8, 0x41,
	0xad, 0x7e, 0x15, 0xb7, 0xbe, 0x7e, 0x29, 0x01, 0xf5, 0xf6, 0xaa, 0xb8, 0x25, 0x29, 0x46, 0x46,
	0x11, 0x48, 0xad, 0x83, 0x18, 0x7e, 0xc2, 0xb1, 0x1f, 0x82, 0xdc, 0x53, 0x20, 0x63, 0x0d, 0x05,
	0xb2, 0x0e, 0x80, 0x1f, 0x14, 0x1b, 0x8c, 0x63, 0x5f, 0x90, 0x2c, 0xd4, 0xd3, 0x7e, 0x38, 0x66,
	0xae, 0x83, 0xec, 0x48, 0x58, 0xeb, 0xd2, 0x23, 0x97, 0x05, 0xdf, 0x21, 0xf4, 0x7d, 0xad, 0x81,
	0x5c, 0x72, 0x5f, 0xd9, 0x23, 0xb0, 0x2c, 0xed, 0xfd, 0xa8, 0xf7, 0x9f, 0xc7, 0xcd, 0xf8, 0x93,
	0xab, 0xcc, 0x1c, 0xd0, 0x05, 0xc2, 0x43, 0xd2, 0x56, 0xc7, 0x43, 0xbc, 0x17, 0x11, 0x56, 0xd5,
	0x01, 0xe2, 0x5d, 0xc5, 0xb7, 0x01, 0x32, 0x2e, 0x6b, 0xb8, 0xa4, 0x81, 0x49, 0xbb, 0x21, 0x9c,
	0x05, 0xde, 0xc5, 0xfa, 0x92, 0xcb, 0xf6, 0x48, 0x28, 0xda, 0xfd, 0xb3, 0x00, 0x16, 0x84, 0x0d,
	0xec, 0x81, 0x45, 0x19, 0x04, 0x58, 0x4c, 0x4c, 0xc9, 0x74, 0xea, 0xf4, 0xad, 0xf9, 0x83, 0x92,
	0xc6, 0x5c, 0x7b, 0xf3, 0xed, 0xd7, 0xfb, 0x0b, 0x10, 0x2e, 0xc7, 0x53, 0x0d, 0xdf, 0x6a, 0x20,
	0x1d, 0xa5, 0x08, 0x6e, 0xcf, 0x76, 0x8c, 0x67, 0x50, 0xbf, 0x75, 0xae, 0x59, 0x05, 0xb0, 0x29,
	0x00, 0x0a, 0xd0, 0x50, 0xbf, 0x51, 0xc9, 0x70, 0x54, 0x6e, 0x62, 0x8e, 0xca, 0x76, 0x14, 0x34,
	0x81, 0x13, 0x65, 0xe9, 0x2c, 0x9c, 0x78, 0x12, 0xcf, 0xc2, 0x99, 0x0a, 0xe7, 0x1c, 0x1c, 0xf1,
	0xb9, 0x82, 0xd8, 0xc2, 0x8f, 0x1a, 0xc8, 0xc4, 0x12, 0x08, 0x77, 0xe6, 0x2c, 0x9a, 0x0a, 0xb3,
	0x5e, 0xfe, 0x07, 0x85, 0x02, 0x2c, 0x09, 0xc0, 0x22, 0xdc, 0x98, 0x0d, 0x38, 0x96, 0x7c, 0xf8,
	0x41, 0x03, 0x97, 0x27, 0x83, 0x08, 0xed, 0xd9, 0x4b, 0x13, 0x03, 0xad, 0xef, 0x9c, 0x5f, 0xa0,
	0x20, 0x6f, 0x0b, 0xc8, 0x4d, 0x78, 0x33, 0x11, 0x12, 0x93, 0x76, 0x78, 0x01, 0x04, 0xaa, 0xca,
	0x83, 0xe3, 0x81, 0xa1, 0x9d, 0x0c, 0x0c, 0xed, 0xe7, 0xc0, 0xd0, 0xde, 0x0d, 0x8d, 0xd4, 0xc9,
	0xd0, 0x48, 0x7d, 0x1f, 0x1a, 0xa9, 0xe7, 0x45, 0xc7, 0xe5, 0x9d, 0x5e, 0xd3, 0x6a, 0x51, 0x2f,
	0xc8, 0x67, 0x69, 0xfc, 0x06, 0x7e, 0x25, 0x4d, 0x79, 0xdf, 0xc7, 0xac, 0xb9, 0x28, 0xee, 0xe0,
	0x3b, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x00, 0xd3, 0x14, 0xe9, 0x3f, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Inflation returns the current minting inflation value.
	Inflation(ctx context.Context, in *QueryInflationRequest, opts ...grpc.CallOption) (*QueryInflationResponse, error)
	// PhaseStep returns the current phase step.
	PhaseStep(ctx context.Context, in *QueryPhaseStepRequest, opts ...grpc.CallOption) (*QueryPhaseStepResponse, error)
	// PhaseProvisions current minting phase provisions value.
	PhaseProvisions(ctx context.Context, in *QueryPhaseProvisionsRequest, opts ...grpc.CallOption) (*QueryPhaseProvisionsResponse, error)
	// EndPhaseStatus returns the current minting phase status.
	EndPhaseStatus(ctx context.Context, in *QueryEndPhaseStatusRequest, opts ...grpc.CallOption) (*QueryEndPhaseStatusResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/sgenetwork.sge.mint.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Inflation(ctx context.Context, in *QueryInflationRequest, opts ...grpc.CallOption) (*QueryInflationResponse, error) {
	out := new(QueryInflationResponse)
	err := c.cc.Invoke(ctx, "/sgenetwork.sge.mint.Query/Inflation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PhaseStep(ctx context.Context, in *QueryPhaseStepRequest, opts ...grpc.CallOption) (*QueryPhaseStepResponse, error) {
	out := new(QueryPhaseStepResponse)
	err := c.cc.Invoke(ctx, "/sgenetwork.sge.mint.Query/PhaseStep", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PhaseProvisions(ctx context.Context, in *QueryPhaseProvisionsRequest, opts ...grpc.CallOption) (*QueryPhaseProvisionsResponse, error) {
	out := new(QueryPhaseProvisionsResponse)
	err := c.cc.Invoke(ctx, "/sgenetwork.sge.mint.Query/PhaseProvisions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EndPhaseStatus(ctx context.Context, in *QueryEndPhaseStatusRequest, opts ...grpc.CallOption) (*QueryEndPhaseStatusResponse, error) {
	out := new(QueryEndPhaseStatusResponse)
	err := c.cc.Invoke(ctx, "/sgenetwork.sge.mint.Query/EndPhaseStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Inflation returns the current minting inflation value.
	Inflation(context.Context, *QueryInflationRequest) (*QueryInflationResponse, error)
	// PhaseStep returns the current phase step.
	PhaseStep(context.Context, *QueryPhaseStepRequest) (*QueryPhaseStepResponse, error)
	// PhaseProvisions current minting phase provisions value.
	PhaseProvisions(context.Context, *QueryPhaseProvisionsRequest) (*QueryPhaseProvisionsResponse, error)
	// EndPhaseStatus returns the current minting phase status.
	EndPhaseStatus(context.Context, *QueryEndPhaseStatusRequest) (*QueryEndPhaseStatusResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Inflation(ctx context.Context, req *QueryInflationRequest) (*QueryInflationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inflation not implemented")
}
func (*UnimplementedQueryServer) PhaseStep(ctx context.Context, req *QueryPhaseStepRequest) (*QueryPhaseStepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PhaseStep not implemented")
}
func (*UnimplementedQueryServer) PhaseProvisions(ctx context.Context, req *QueryPhaseProvisionsRequest) (*QueryPhaseProvisionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PhaseProvisions not implemented")
}
func (*UnimplementedQueryServer) EndPhaseStatus(ctx context.Context, req *QueryEndPhaseStatusRequest) (*QueryEndPhaseStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndPhaseStatus not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sgenetwork.sge.mint.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Inflation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInflationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Inflation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sgenetwork.sge.mint.Query/Inflation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Inflation(ctx, req.(*QueryInflationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PhaseStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPhaseStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PhaseStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sgenetwork.sge.mint.Query/PhaseStep",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PhaseStep(ctx, req.(*QueryPhaseStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PhaseProvisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPhaseProvisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PhaseProvisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sgenetwork.sge.mint.Query/PhaseProvisions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PhaseProvisions(ctx, req.(*QueryPhaseProvisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EndPhaseStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEndPhaseStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EndPhaseStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sgenetwork.sge.mint.Query/EndPhaseStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EndPhaseStatus(ctx, req.(*QueryEndPhaseStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sgenetwork.sge.mint.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Inflation",
			Handler:    _Query_Inflation_Handler,
		},
		{
			MethodName: "PhaseStep",
			Handler:    _Query_PhaseStep_Handler,
		},
		{
			MethodName: "PhaseProvisions",
			Handler:    _Query_PhaseProvisions_Handler,
		},
		{
			MethodName: "EndPhaseStatus",
			Handler:    _Query_EndPhaseStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sgenetwork/sge/mint/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryInflationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInflationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInflationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryInflationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInflationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInflationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Inflation.Size()
		i -= size
		if _, err := m.Inflation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryPhaseStepRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPhaseStepRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPhaseStepRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryPhaseStepResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPhaseStepResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPhaseStepResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PhaseStep != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PhaseStep))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPhaseProvisionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPhaseProvisionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPhaseProvisionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryPhaseProvisionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPhaseProvisionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPhaseProvisionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.PhaseProvisions.Size()
		i -= size
		if _, err := m.PhaseProvisions.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryEndPhaseStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEndPhaseStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEndPhaseStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryEndPhaseStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEndPhaseStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEndPhaseStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsInEndPhase {
		i--
		if m.IsInEndPhase {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryInflationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryInflationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Inflation.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryPhaseStepRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryPhaseStepResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PhaseStep != 0 {
		n += 1 + sovQuery(uint64(m.PhaseStep))
	}
	return n
}

func (m *QueryPhaseProvisionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryPhaseProvisionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PhaseProvisions.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryEndPhaseStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryEndPhaseStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsInEndPhase {
		n += 2
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInflationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInflationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInflationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInflationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInflationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInflationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inflation", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Inflation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPhaseStepRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPhaseStepRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPhaseStepRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPhaseStepResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPhaseStepResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPhaseStepResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhaseStep", wireType)
			}
			m.PhaseStep = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PhaseStep |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPhaseProvisionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPhaseProvisionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPhaseProvisionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPhaseProvisionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPhaseProvisionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPhaseProvisionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhaseProvisions", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PhaseProvisions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEndPhaseStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEndPhaseStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEndPhaseStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEndPhaseStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEndPhaseStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEndPhaseStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsInEndPhase", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsInEndPhase = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
